/* eslint-disable max-len */
export const array = {
  title_homes: 'homes',
  title_learn: 'Learn',
  title_support: 'support',
  subtitle_sell: 'Sell',
  subtitle_b2b: 'B2B',
  listings: 'Listings',
  sell_to_us: 'Sell to us',
  sell_with_us: 'Sell with us',
  second_home_hunter: 'Second home hunter',
  homeowners: 'Homeowners',
  agents: 'Agents',
  developers: 'Developers',
  investors: 'Investors',
  scheduling: 'Scheduling',
  travel: 'Travel',
  company: 'Company',
  blog: 'Blog',
  community: 'Communities',
  agent_support: 'Agent support',
  faqs: 'FAQs',
  contact: 'Contact',
  privacy: 'Privacy policy',
  sitemap: 'Sitemap',
  favourites: 'Favourites',
  bottom1: '© 2022 OO.',
  bottom2: 'All rights reserved',
}

export const dataSignIn = {
  title: 'Sign In',
  forgot: 'Forgot password?',
  recover: 'Recover',
  noAcc: 'Don’t have an account?',
  demo: 'Demo',
  button: 'Next',
  enter: 'Enter new password',
  secure: 'Secure Code',
  text: 'This code will expire in 3:00',
  success: 'Password change was successful',
}

export const bookingPage = {
  h1: 'Book a stay in your second home',
  property4: {
    title: 'Whole home listed by',
  },
  response_form: {
    title: 'Thank you!',
    text1: 'Your sabmission has been received!',
    button: 'CLOSE',
    text2: 'Something went wrong, please try again',
  },
  property_form: {
    title: 'Like this home? Still have questions?',
    text: null,
    name: 'NAME*',
    surname: 'SURNAME*',
    phone: 'PHONE*',
    email: 'E-MAIL*',
    title2: 'I’m a:',
    select1: 'AGENT',
    select2: 'DEVELOPER',
    select3: 'BUYER',
    select4: 'SELLER',
    select5: 'HOMEOWNER',
    select6: 'OTHER',
    comment: 'Leave a comment',
    button: 'Send',
    button2: 'Contact us',
  },
  house: {
    button1: 'Want this house',
    share_ownership_8: '1/8 Ownership',
    share_ownership_4: '1/4 Ownership',
    how_we_price_8: 'How we priced this 1/8 share',
    how_we_price_4: 'How we priced this 1/4 share',
    how_we_price_text:
      'We give our homes a full design makeover, manage all aspects of LLC formation, and find qualified owners.',
    share_price: 'Purchase price',
    whole_home_price: 'Whole home price',
    upgrades_closing: 'Home Upgrades & Closing',
    upgrades_closing_more: 'Interior design, furnishings, inspection & title',
    service_fee: 'Oww Service Fee',
    service_fee_more: 'Buyer aggregation, legal & financing',
    total_8_price: 'Total 1/8 Ownership',
    total_4_price: 'Total 1/4 Ownership',
    whole_home_value: 'Whole Home Value',
    attributes: 'Attributes',
    address: 'Address',
    owners_expenses_pdf: 'Owners expenses (PDF)',
    about_coownership: 'About Coownership',
    about_this_house: 'About this house',
    video: 'Property video',
    similar_homes: 'Similar Homes Nearby',
    agent: 'Whole home listed by',
    button_roll_up: 'Roll up',
    button_roll_down: 'Roll down',
  },
  monthly_expenses: {
    title: 'Estimated\r\nMonthly owner Expences',
    text: 'Oww owners share home operating expences pro rata. Expences are passed along monthly, at cost - no surprise fees or hidden costs',
    property_taxes: 'Property taxes',
    cleaning_fee: 'Cleaning Fee',
    property_management: 'Property management',
    maintenance: 'Maintenance*',
    utilities: 'Utilities',
    management_fee: 'Oww management fee**',
    insurance: 'Insurance',
    repairs_reserve: 'Repairs Reserve',
    monthly_contribution: 'Monthly Contribution',
    annual_total: 'Annual Total',
    text2:
      '* Includes preventive (e.g. roof). recurring (e.g. landscaping)\r\n** Fixed €99 fee for LLC oversight, technology and owner support',
  },
}

export const options = { month: 'long', day: 'numeric' }
